travis:
  secure:
    BINSTAR_TOKEN: fpe8aXR8J9KP0HDMB92An8u0z+/knvlKNSe8/mvI5etSpXUvN7x8fk1VRGgP2OwTbLf5i8AXzP/lKvDZLMRlZqObIDdd6Ye6ZK9vthQ4B9vm8OuCVVL2+uGkdOPjhKc0yCdNB98LVUyzOuKajciPGz6Ypl5I+dJcKcTYJMDQ9SXhy06akV2W2HLW1xlNDvnzzIBdLApJMXntmYqpaqbU2/HNnVnOAzTm0zlrEp+0ApyvdN9U6Jatjnbh9rNSLbi4gBTJxtymSj+Gf2IguzCJ5GxjYa1FaKv8xx1UUXkRhFJjwVooo7x3uV3Xr8uNDbFHKZ0F0QX6ekkXf32kM2EYmKgtqc14eG/Elx6OSxkEJmP3jp8N5MC/DgiMybwTZbBJcNRfZbFpbLrF+Um0hZ6dvLUNu1Y2pdlQTSdnXkbJMi9CtWo3SU8eOezbfS0oqcCKLMV0khyX7d3XaFhg0WfJA4UX6A6yK5+ptlLypC/nmJiqJGto9b71xwr8nzc5npcgYUv2aEx0JOL7K98Sy/+LbKKChOyrSeSs4xW5QTvJBuJDXYO6Jy3N5yebNQK4VW1FKL54Qk1CmFgRarkm8/DPH111D08yxVIFfsLjw+f9wC57F1cgx6n8qlwuvfyDDmRZy6UyOOSWmA1jgUToK518r3ZOUiztXiPf6nTA2/apVsg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
