travis:
  secure:
    BINSTAR_TOKEN: b7wkTVpnORmIKfcK/VzcfGujoXFtzSel6b6rseON+1tqTphp01FuPFBIjhLR4181PnJ8Y/Vkytq5Ju3s9e3gj0kOsg9T50heVn/PU5DGVc2N7+KbK1NNELEwi8u/qBn1mOJCjtkW6BAgRPFgVX8olT1Kdub9XgnRRQOgWfU0ztEAZsaAZba14jux13/ZYhPd2H/OfowSpI0nzZBv33pCxi6eMEJYFg5UcIEbdHtnzdda4iuwLK0WtOcwhz/G3rr3yAuxi6yHYZlp+GYjV7iaFQZoI38bP2AMX9YDgMp0DtAxwcswPqdns1zTJQlONJ93uXCtjtr1J/DHqqU6tScnsMNEsr0CC8NXU+i+EJdu7C55CEid6yfys+V9LaG8qWI/xvEOF8QFxXjsSwIxICtavWRYfxV9noKSMZSGI60V1UEKPjqGRJeJRTEnDt6XD3z23yScH3d0Z1b5P7xEQiVYk+Kx5JFPiuljx7Q1N46mq0P34CgXUquJEPomyx9FhNH5M/EDRImKinqTyAal26DFrOmtZyAXmPlYsjwAYdYhy0z7gmt2ZHlC3SWWPXy9ULpR0iIfKnwVM7l10+CmTbkKX0y30tRyeBONRC6UXD8btyKBi54QL6HqTTZUswiRt8uwGDgTmCoYeMbsySdLEEweZvRYuwvhT/M2ljlZX++doEo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
